### ISSUE TITLE
colorbox inline not working

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/colorbox#38]
The inline feature is not working on my site. After clicking on an image, the colorbox frame appears and tries to load the image, which never happens. It stays gray. I don't know how to debug this. The js console doesn't show anything wrong. Any idea? Thanks.

**Comment by jromine** [comment]
Does the Backdrop log provide any further info?

**Comment by indigoxela** [comment]
Possibly related: https://www.drupal.org/project/colorbox/issues/3262281

**Comment by jenlampton** [comment]
Thanks for the reference @indigoxela ! The final fix for that problem is in a patch in https://www.drupal.org/project/colorbox/issues/3262686#comment-14473801, and new a release (for Drupal and Backdrop) should be coming out in the next few days.

**Comment by jenlampton** [comment]
I ended up getting cold feet about making the release today because the external library we are including (DOMpurify) has some security issues that I'd like to confirm don't lead to security issues with websites running Colorbox, so instead I've created a 1.x-1.16.1 release that contains all the recent bug-fixes, and I've committed the DOMpurify fix into -dev.

If you are waiting for this fix, please update to the -dev release, and not today's 1.16.1 release. I'm hoping a 1.17.0 will be coming along shortly also.

**Comment by jenlampton** [comment]
The new release is out today! 
https://github.com/backdrop-contrib/colorbox/releases/tag/1.x-2.17.0
