### ISSUE TITLE
Colorbox and external URLs (iframe now, next version without)

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/colorbox#39]
As [posted in the Backdrop Forum](https://forum.backdropcms.org/forum/troubles-colorbox-widget), Colorbox and other modules that depend on it (e.g. YouTube Field Colorbox) will not load external URLs in a Colorbox after the latest security fix.

Apparently there is already a fix for this and other issues produced by the security update. See: https://www.drupal.org/project/colorbox/issues/3262686#comment-14453187

**Comment by philippeg2** [comment]
Hi,
I would be really happy if this problem could be solved because my users were used to ergonomics before this problem and this bug us a real problem of fluidity on the whole site because this function was used on all video playbacks and this site is dedicated to youtube videos, many thanks if this issue could be addressed as soon as possible.

**Comment by olafgrabienski** [comment]
Not sure if it helps, but the [notes of the last release](https://github.com/backdrop-contrib/colorbox/releases/tag/1.x-2.16.0) mention the topic and a workaround:

> colorbox_load is now restricted to internal Drupal paths only, and will not load external URLs. You can still use colorbox_inline with an iframe to load external content into a colorbox.

**Comment by philippeg2** [comment]
"Not sure if it helps, but the [notes of the last release](https://github.com/backdrop-contrib/colorbox/releases/tag/1.x-2.16.0) mention the topic and a workaround:

    colorbox_load is now restricted to internal Drupal paths only, and will not load external URLs. You can still use colorbox_inline with an iframe to load external content into a colorbox."  i saw  the notes that what does that mean ? That we can no longer use of window parameters ? These parameters related to the size of the viewing window still exist and either they are no longer operational and therefore it is clearly a functional regression, which means that Backdrop no longer has any module allowing you to view a video in a window, or it is a bug of the new version which will be corrected ....

**Comment by olafgrabienski** [comment]
> i saw  the notes that what does that mean ? That we can no longer use of window parameters ? These parameters related to the size of the viewing window still exist and either they are no longer operational and therefore it is clearly a functional regression, which means that Backdrop no longer has any module allowing you to view a video in a window, or it is a bug of the new version which will be corrected ....

Unfortunately, I don't know what it means exactly, just wanted to give a hint and keep the ball rolling, hoping that somebody with more insight and coding skills will have a look. I saw only now that the discussion already continued in the [Forum thread](https://forum.backdropcms.org/forum/troubles-colorbox-widget). Maybe it's worth to report the issue also in the [YouTube field](https://github.com/backdrop-contrib/youtube) queue and/or ask @jenlampton what she thinks about it, as she maintains both modules.

**Comment by jenlampton** [comment]
The current version of colorbox does still allow external URLs to be used, but the links need to be loaded in an iFrame (add `&iframe=true` to the end of the colorbox link). The next version of colorbox will include a fix that will allow them to be loaded without the iframe again, and also without the security vulnerability :)

**Comment by jenlampton** [comment]
I ended up getting cold feet about making the release today because the external library we are including (DOMpurify) has some security issues that I'd like to confirm don't lead to security issues with websites running Colorbox, so instead I've created a 1.x-1.16.1 release that contains all the recent bug-fixes, and I've committed the DOMpurify fix into -dev.

If you are waiting for this fix, please update to the -dev release, and not today's 1.16.1 release. I'm hoping a 1.17.0 will be coming along shortly also.

**Comment by jenlampton** [comment]
The new release is out today! 
https://github.com/backdrop-contrib/colorbox/releases/tag/1.x-2.17.0

**Comment by philippeg2** [comment]
Thanks
