### ISSUE TITLE
Remove dependance on libraries.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/colorbox#9]
This is a great example of a module that should bundle it's library. The name of the module is colorbox, the name of the library is colorbox. If any other module needs the colorbox library, then it should depend on this one. (not on a libraries API).

**Comment by klonos** [comment]
@jenlampton although what you describe is a valid use case, libraries have another couple of purposes:
1. They are a means to minimize the download size of module packages (although I admit that ease of use and work out-of-the-box are more important).
2. They help the end user update any 3rd-party libraries independently from module releases. For instance, they might require the use of either customized ones (unreleased, dev or beta builds or even GitHub forks for example) or newer released, stable versions without having to request the module maintainer(s) to update their code and also release a newer version of the entire module just to upgrade the library. If people replace the in-built library with a patched version that fixes certain issues and then a new version of the module comes out with module-specific fixes but not an updated version of the library, then people need to remember to re-patch. If they forget how/why because time has passed and they forgot that they were using a custom version of the library in the first place, then they'll think that the new version of the module "breaks things".

**Comment by jenlampton** [comment]
I agree 1 is a non-issue. The end result of bundled code is likely to be
smaller libraries anyway, because the developers know which parts of that
library can be removed, where the site builder won't.

2 is an extremely minor use-case. In my 10 + years of Drupal development I
have rarely needed a newer library than what was supported by a module. On
the other hand, I have had several problems with installing a new,
unsupported version of a library, then needing to go back in time until I
found one the module actually worked with. Frustrating.

A module will often break if a different version of the library is dumped
into it. That sort of change should be thoroughly tested, and if it does
actually work, the module should be updated to include the newer version of
library so that everyone else in the community can benefit from that change
too.

Here in backdrop were supposed to value site-builders over developers. That
means making making installation of modules w libraries easier. 1 Bundle
the files for an easier download, and better user experience in general. 2
don't make the site builder install any number of library versions trying
to find one that works. The maintainer knows which one works, so let's
bundle it. If someone needs something else (edgecase), let them do the
extra work then. Let's not make everyone do the extra work every time.

The one use-case for libraries API that is still valid is multiple projects
needing the same library. In the case of colorbox, I think the colorbox
module should be the source of that library, other modules that need it can
require this module. It's lightweight, and has the  namespace. (I'm also
not sure we have any other projects that need this library yet.)

**Comment by wesruv** [comment]
Great points all, I like Jen's thinking. I'd agree that it's not often that I need a different version, and at that point you can fork the module, or do something else like include it in your theme.

I like the 'it just works' approach that favors site builders.

**Comment by klonos** [comment]
> I like the 'it just works' approach that favors site builders.

Of course I like that approach too. It's just that with D7, many times I had to update some odd 3rd party libraries to fix glitches and because the module did not support libraries.module, I had to replace the in-built library. I would leave the site alone for a while till some security update came out, then upgrade core and various contrib modules only to have the site owner come back to me a few days later saying "We are having that issue again". Of course I had to scratch my head for a few minutes before I realized what has happened: one of the modules I upgraded was the one I "hacked", so replacing it with the newer version that came out (including the security fixes) reverted the 3rd party library to a non-updated version. If the 3rd party library was kept in a `/sites/all/libraries` folder, that would have never happened.

Then, once I would "fix" the issue, I'd turn to the contrib module queue to try to ping the maintainers to upgrade the library where I would at best wait for a few months before that happens - if it ever did. I understand all that, I know that open source software is developed mostly in people's spare time, but in Drupal-land the issue queue was/is soooo damn slow and I personally felt like I had to put up a fight each time to convince people to upgrade. Perhaps it was due to the "noise" in the queues coming from the many people abusing the priority tag and the many "fix my broken site for me" issues that made the maintainers neglect the queue, but the end result was pure frustration for folks like me that filed legitimate "here's how to fix this issue, can you please upgrade the 3rd party lib to latest" issues. Perhaps it was pure lack of time though.

> ... and at that point you can fork the module,

True, in Backdrop land we are harnessing the powers of GitHub (and I have myself mastered a few aspects of it), but for the simple, non-coder site builder, how easy is it to fork a module in order to include an up to date version of a 3rd party? Wouldn't it be easier to just place the updated version under `/libraries` and then have things "simply" work? Then again, say they do learn how to fork in GitHub. How would they keep their module up to date and be notified of newer versions? Their fork would not live in `https://github.com/backdrop-contrib` and thus no "official" releases would ever reach their notification system.

So, just to make it clear, I'm not (that much) against shipping with any required 3rd party library. I just don't think it is a smart move to completely remove the `/libraries` _support_ (@jenlampton in this issue calls it a _dependency_) that a site builder can take advantage of in order to "safely" replace/override the built-in library. That's how libraries work right? Placing a library with the same filename under `/libraries` makes it so that it takes precedence over the built-in one. Right?

**Comment by klonos** [comment]
> ...or do something else like include it in your theme.

When I started with Drupal, I used to use contrib themes. It took me quite a while till I started making my own. We shouldn't be assuming that new users are themers. And with the very pretty Basis as the default theme (especially when @wesruv implements the color-picking-automatically-adapts-my-entire-site-identity feature 👍 😉 ), they might not even be bothered to install any other theme. Asking them to include any updated/custom version of a 3rd party lib in such cases would mean either "hacking core (themes)" or learning how to subtheme. Again not very optimal for non-coder, non-themer site builders.

**Comment by klonos** [comment]
...so as you said @jenlampton, 1 is pretty much a non-issue (that's why I am not arguing that much about it), but 2 is an important one. The golden line I guess would be to be shipping with a built-in 3rd party library so that people installing the module don't have to do any additional tasks, but we should also allow the 3rd party library to be easily replaced (using `/libraries` - without having to fork projects etc).

**Comment by jenlampton** [comment]
Average people (sorry super-@klonos, you are no average user) will not be replacing libraries. It's more likely that things will break if they do that, than anything getting better. It _should_ be hard - in the same way that changing/hacking the code in a module (or in core!) is "hard".  The consequences are the same (stuff most likely broken, and updates difficult.)

Most people will be happy with a module that "just works" and will not need features that only exist in latest version of the included library, so it won't be necessary very often. However, when it is necessary, people should be aware that making that kind of change is not "supported" in the same way that modifying any of the other code in the module is not "supported". It's still possible of course -- everything is still open source -- but making it easy for unsuspecting people to shoot themselves in the foot should be avoided. Providing shoot-my-foot APIs is something that happened too much in Drupal, and I would like to try to do better in that area for Backdrop.

I do expect that some people will disagree, and libraries can still exist in contrib for those who need to swap out a library. But for the majority of Backdrop sites, it shouldn't ever be necessary :)

**Comment by wesruv** [comment]
I think we can do a better job of keeping external libraries up to date because Github is a lower bar than D.org, I think we'll have more people willing to help keep things up to date.

I'm also hoping that we can get a more robust `hook_library()` (we mentioned this in https://github.com/backdrop/backdrop-issues/issues/2228). That would make it easier to update included libraries for those people that run into the issues @klonos is describing.

**Comment by laryn** [comment]
I ran into a fatal error due to #4 and taking this latest commit makes installation easier and solves that issue, too. Seems to be functioning well.
